/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/head.glb --transform -o src/components/Head.jsx -k -K -r public 
Files: public/head.glb [416.54KB] > D:\Sudeepto\floating-head\src\components\head-transformed.glb [414.14KB] (1%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useLoader } from '@react-three/fiber'
import { easing } from 'maath'
import * as THREE from 'three'

export function Head(props) {

  const group = useRef()

  const { nodes, materials } = useGLTF('/head-transformed.glb')

  const surfaceImperfection = new useLoader(THREE.TextureLoader, '/surf_imp_02.jpg')
  console.log(surfaceImperfection)
  surfaceImperfection.wrapT = THREE.RepeatWrapping
  surfaceImperfection.wrapS = THREE.RepeatWrapping
  const customMaterial = new THREE.MeshPhysicalMaterial({
    color: 'white',
    metalness: 1,
    roughness: 0.75,
    roughnessMap: surfaceImperfection
  })
  useFrame((state, delta)=>{
    easing.dampE(group.current.rotation, [-state.pointer.y *0.4, state.pointer.x, 0, 0.25, delta])
  })

  return (
    <group ref={group}{...props} dispose={null}>
      <group name="Scene">
        <mesh name="BSurfaceMesh" geometry={nodes.BSurfaceMesh.geometry} material={customMaterial} />
      </group>
    </group>
  )
}

useGLTF.preload('/head-transformed.glb')
